### PR TITLE
Bring the library to the current age

### PR DESCRIPTION
**Pull request by loxs**
I have added dune files and (hopefully)converted it to modern js_of_ocaml.
Also upgraded to latest c3js, which seems to work without issues (at lest for the example application)

Of course this makes it incompatible with oasis, but I am still an ocaml newbie and just know dune, so that was the only way to make it work for me.

### CODE REVIEW

**Comment by samoht** [comment]
@loxs Seems that our PRs just crossed! I've just ported the library to dune/ppx in #21

**Comment by samoht** [comment]
@djs55 I guess https://github.com/djs55/ocaml-c3/pull/20/commits/c0548d147cc00446ae35a4a69fb078d9f78c942f could be cherry-picked as well

**Comment by djs55** [comment]
@samoht good idea.

@loxs thanks for the patch!

**Comment by djs55** [comment]
I've cherry-picked the patch and released 0.4.0: https://github.com/ocaml/opam-repository/pull/12412

Thanks again!

**Comment by loxs** [comment]
Wow, what are the chances :D

**Pull request closed without merging**
